[Service]
Environment=LLM_SMALL_CUDA_VISIBLE_DEVICES=1
Environment=LLM_SMALL_VLLM_GPU_MEMORY_UTILIZATION=0.50
Environment=LLM_SMALL_VLLM_TENSOR_PARALLEL_SIZE=1
Environment=LLM_SMALL_LLAMA_CPP_N_GPU_LAYERS=-1
Environment=LLM_SMALL_LLAMA_CPP_PARALLEL=1
